import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import NextAuthSessionProvider from "./provider";
import Footer from "./components/Footer";
import { Toaster } from "../components/ui/sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
      <NextAuthSessionProvider>
        <div className="mx-6 md:mx-16">
          <Header/>
          <Toaster/>
        {children}
        <Footer />
        </div>
      </NextAuthSessionProvider>
        </body>
    </html>
  );
}
